services:
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_SEARCH_JAVAADDITIONALOPTS: "-Dnode.store.allow_mmap=false"
    ports:
      - "9000:9000"
  db:
    image: postgres:latest
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "9999:5432"
  db_init:
    image: postgres:latest
    volumes:
      - ./init/db.dump:/db.dump
    environment:
      - PGPASSWORD=sonar
    command: pg_restore -h db --no-owner --no-privileges -d sonar -U sonar db.dump
    depends_on:
      db:
        condition: service_started
    restart: on-failure